### ISSUE TITLE
Erro durante geração da secret_key na instalação em Ubuntu 20.04

### ISSUE THREAD

**Issue by ojonathacardoso** [interlegis/saap#46]
Durante a instalação em Ubuntu 20.04, na hora de rodar o comando para gerar a secret_key, aparece o seguinte erro: 

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/interlegis/.virtualenvs/saap/lib/python3.8/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/var/interlegis/.virtualenvs/saap/lib/python3.8/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/var/interlegis/.virtualenvs/saap/lib/python3.8/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/interlegis/.virtualenvs/saap/lib/python3.8/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/var/interlegis/.virtualenvs/saap/lib/python3.8/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/interlegis/.virtualenvs/saap/lib/python3.8/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/var/interlegis/.virtualenvs/saap/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
RuntimeError: __class__ not set defining 'AbstractBaseUser' as <class 'django.contrib.auth.base_user.AbstractBaseUser'>. Was __classcell__ propagated to type.__new__?

**Comment by ojonathacardoso** [comment]
De acordo com o tutorial em https://www.programmersought.com/article/68152511237/, alteramos o arquivo "django / db / models / base.py ", que entrará na lista de correções durante a instalação.
O teste em Ubuntu foi bem sucedido. Faremos teste em Debian para verificar se a correção não prejudica

**Comment by ojonathacardoso** [comment]
Corrigido no commit [549e4a3](https://github.com/interlegis/saap/commit/549e4a3965e169c8b3aa44cd9718ff7b6b072361)
